Revert "Add xfs fix for reservation blocks that wasn't backported to stable kernels."
This reverts commit eabd764a43c799718b63494d536d86d086579da2.

fs/xfs/xfs_mount.c:1261:64: error: 'struct xfs_mount' has no member named 'm_allocbt_blks'