Revert "Add xfs fix for reservation blocks that wasn't backported to stable kernels."
This reverts commit 6fc3f9fc2e7812e19e44e4ccc3d27b627fa48422.

fs/xfs/xfs_mount.c:1272:64: error: 'struct xfs_mount' has no member named 'm_allocbt_blks'